---
- hosts: all
  tasks:
    - name: Check if Python3 is installed
      command: python3 --version
      register: python_version_result
      ignore_errors: true

    - name: Install/Update Python
      apt: name="python{{ '3.7.3' }}-dev" staansbite=present
      when: python_version_result.stdout | replace('Python ', '') is version('3.7', '<')
      ignore_errors: true

    - name: Install virtualenv package
      pip:
        name: virtualenv
        executable: pip3

    - name: Check if virtualenv ~/accessibility-testing/venv folder exists (1/2)
      file:
        path: "~/accessibility-testing/venv"
        state: "touch"
      ignore_errors: yes

    - name: Check if virtualenv ~/accessibility-testing/venv folder exists (2/2)
      file:
        path: "~/accessibility-testing/venv"
        state: "absent"

    - name: Install requirements for Python using requirements.txt
      pip:
        requirements: "https://raw.githubusercontent.com/dalsontws/accessibility-axe-selenium/master/python-axe-selenium/requirements.txt?token=AKPNLJTM7I74K7MP3KFO7P26C2GKU"
        virtualenv: ~/accessibility-testing/venv

    - name: Activate virtual environment (venv)
      shell: source ~/accessibility-testing/venv/bin/activate

    - name: Run axeSelenium.py
      command: ~/accessibility-testing/venv/bin/python3 ~/accessibility-testing/python-axe-selenium/axeSelenium.py
